Feat: RunningRecord controller record 추가 api 추가
dnd-side-project/dnd-11th-2-backend pull request #52
Opened 2024-08-07 11:45 UTC by Jaewon-pro

## 🔗 이슈 연결

- close #30 

## 🚀 구현한 API

- POST `api/v1/running-records`: 혼자 뛰기 러닝 기록 추가

## 💡 반영할 내용 및 변경 사항 요약

- 혼자 뛰기 러닝 기록 추가 API를 추가해요.
- `RunningRecordService` addRunningRecord 메서드에서는 request 값이 올바른지 검증하고 값을 저장해요
  - start_at이 end_at보다 빨라야 함
  - route의 좌표들은 2개 이상이어야 함
- `RunningEmoji`에 client와 정의한 enum 이름에 맞게 수정해요
  - NORMAL -> SOSO

## 🔍 리뷰 요청/참고 사항

- `MemberEntity`에 `Badge` 엔티티가 없어서, fetch join을 사용할 수 없어요.
   그래서 JPQL을 사용해서 dto projection하려니, 문자열로 SQL을 적는거랑 다름이 없는 것 같아요.
  - QueryDSL이나 Jooq와 같은 프레임워크를 도입하면 좋을 것 같아요 
  - 지금은 member가 badge가 있더라도, profileUrl은 null을 반환해요
    - [FIXME 주석](https://github.com/dnd-side-project/dnd-11th-2-backend/compare/feature/%2330/add-running-record?expand=1#diff-4fd8601b8962191478429d48fd085977a5f43d1770436572b57a1d6857870b93R43)
- 챌린지 부분은 아직 구현되지 않은 상태여서, request, response 스키마에만 id로만 존재해요.
  - 챌린지 기능이 있어야 한다는 점은 [TODO 주석](https://github.com/dnd-side-project/dnd-11th-2-backend/compare/feature/%2330/add-running-record?expand=1#diff-4fd8601b8962191478429d48fd085977a5f43d1770436572b57a1d6857870b93R46)으로 남겨두었어요

2024-08-07 18:09 UTC, hee9841 requested changes
수고하셨습니다. 코드가 전반적으로 깔끔한 것 같아요👍

2024-08-07 18:09 UTC, hee9841 commented on src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
> +            @MemberId long memberId, @RequestBody RunningRecordRequest request) {
`@Valid` 추가하는게 좋을 것 같아요!
```suggestion
            @MemberId long memberId, @Valid @RequestBody RunningRecordRequest request) {
```

2024-08-07 18:09 UTC, hee9841 commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
각각의 러닝 기록 조회하는 거와 응답이 같을 것 같아서
`RunningRecordSavingResponse` 보다는 러닝 디테일 응답을 나타내는 네이밍이 좋을 것 같아요.😊

2024-08-07 18:09 UTC, hee9841 commented on src/main/java/com/dnd/runus/application/running/RunningRecordService.java
> +        }
👍

2024-08-08 04:36 UTC, Jaewon-pro commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
`RunningRecordDetailResponse`이란 이름이 애매하긴 한데,
더 좋은 이름이 생각나지 않네용

2024-08-08 04:36 UTC, Jaewon-pro commented on src/main/java/com/dnd/runus/application/running/RunningRecordService.java
> +        // TODO: 챌린지 기능 추가 후 수정
이 부분은 스크럼때, 여기 이슈에서 논의해보면 좋을 것 같아요!
- #39 
- 필요한 기능 정리
- 테이블 구조

2024-08-08 06:49 UTC, hee9841 commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
🤔

2024-08-08 06:50 UTC, hee9841 commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
`MemberRunningDetailRecordResponse`는 어떠신가요?🤔
뭔가 더 좋은 이름이 생각나지 않네요

2024-08-08 07:11 UTC, Jaewon-pro commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
`RunningRecordReportReponse`로 하면 어떨까요?

running_record 라는 테이블 명은 중간에 단어 없이 그대로 추가하면 좋을 것 같아요

그리고 `RunningRecordDataDto`도 이름을 `RunningRecordMetricsDto`로 바꾸면 이름이 좀더 명시적인 것 같아요

2024-08-08 10:53 UTC, hee9841 submitted a review, later dismissed
수고 많이셨습니다 👍

2024-08-08 11:22 UTC, Jaewon-pro commented on src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSavingResponse.java
클래스 이름들 변경했는데 확인 부탁드려요!
- https://github.com/dnd-side-project/dnd-11th-2-backend/pull/52/commits/b094847a15fd2f8bb81a560a28766f22bd71a6b9

2024-08-08 11:45 UTC, hee9841 approved these changes

2024-08-08 11:56 UTC, merged